[package]
name = "moves"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
bincode = "1.3.3"
serde = { version = "1.0.197", features = ["derive"] }
rand_core = "0.6.4"
secp256k1 = { version = "0.28.2", features = ["rand-std", "hashes-std"] }
rand = "0.8.5"
